#!/usr/bin/env python3
"""Family 1: intent routing over 15 business domains.

Per (domain, intent) the module owns
  * direct utterances (`ph`) that contain the intent's own vocabulary,
  * paraphrases (`para`) that deliberately avoid the gold option's keywords,
  * implicit situations (`sit`) that describe a state of the world with no
    intent keyword at all,
  * keywords (`kw`) used to plant *wrong* options' vocabulary in distractor
    sentences and in negated contrasts.
All of these lists are halved by `core.split_pool`, so the frozen benchmark and
the training pool never share an utterance template.
"""
from . import core

FAMILY = "intent_routing"

# key, what, not_for, ph[], para[], sit[], kw[]
DOMAINS = {
"ecommerce": ("an online retail store", [
 ("order_tracking", "Delivery status, tracking numbers, shipment progress and late parcels", "Payments, returns or account access",
  ["Where is my parcel? The tracking number has not moved for six days.",
   "My order shipped last week but the tracking page still shows the same scan.",
   "Can you tell me when the shipment for my order will actually be delivered?"],
  ["Nothing has arrived and the courier's page has said the same thing since Tuesday.",
   "I would like a realistic arrival date for the box I am waiting on."],
  ["The doorbell never rang and the front step has been empty all week.",
   "My neighbour received her box on the same day I ordered mine and mine is still nowhere."],
  ["tracking", "delivery status"]),
 ("return_request", "Sending an item back, exchanges, return labels and restocking", "Delivery delays or billing errors",
  ["I would like to return the {product} I bought and get a return label.",
   "Please start a return for the {product}; it is the wrong size.",
   "How do I send the {product} back for an exchange?"],
  ["The {product} does not fit and I want to send it back for a different size.",
   "I no longer want to keep the item and would like to post it back to you."],
  ["The jacket is two sizes too big and the tags are still attached.",
   "I ordered two colours intending to keep only one of them."],
  ["return label", "exchange"]),
 ("billing_dispute", "Charges, invoices, refunds of money already taken and payment methods", "Shipping questions or product defects",
  ["I was charged twice for the same order and want the duplicate charge reversed.",
   "My invoice shows ${amount} but the checkout page quoted a lower price.",
   "The refund you promised has still not reached my card."],
  ["Two identical debits from you appeared on my statement on the same day.",
   "The amount taken from my account does not match what the basket said."],
  ["My bank statement lists your company twice on the same date for the same sum.",
   "The sum that left my account is forty euros higher than the order confirmation."],
  ["charge", "invoice"]),
 ("product_defect", "Faulty, broken or malfunctioning goods and warranty claims", "Delivery or billing questions",
  ["The {product} stopped working after two days and will not switch on.",
   "The {product} arrived with a cracked casing and rattles when shaken.",
   "My {product} overheats within minutes of being plugged in."],
  ["The item I received does not do what it is supposed to do at all any more.",
   "Something inside the unit is loose and it shuts itself off constantly."],
  ["There is a burning smell whenever I plug the unit into the wall socket.",
   "The screen went black on the second day and has stayed black since."],
  ["faulty", "warranty"]),
 ("account_access", "Sign-in problems, passwords, two-factor codes and profile security", "Orders, payments or deliveries",
  ["I cannot log in to my account even after resetting the password twice.",
   "The two-factor code never arrives on my phone so I am locked out.",
   "Someone else appears to have signed in to my profile from another country."],
  ["Every attempt to get into my profile is rejected even with the new credentials.",
   "The verification message that is supposed to let me in never shows up."],
  ["The site keeps sending me back to the same screen no matter what I type.",
   "My saved addresses have changed and I never touched them."],
  ["password", "sign-in"]),
 ("sales_enquiry", "Pricing, quotes, bulk orders, upgrades and pre-sales questions", "Problems with an existing order",
  ["Do you offer a volume discount if we order {n} units of the {product}?",
   "Please send a quote for {n} {product}s delivered to {city}.",
   "Which plan includes priority handling for business customers?"],
  ["We are considering a larger purchase and would like to know what rate applies.",
   "Before we commit, what would {n} of them cost us in total?"],
  ["Our procurement team is comparing three suppliers for a large seasonal order.",
   "We are opening a second site and will need matching equipment for it."],
  ["quote", "discount"]),
]),
"banking": ("a retail bank", [
 ("card_fraud", "Unrecognised transactions, stolen cards and suspected fraud", "Ordinary fee questions or loan applications",
  ["There are transactions on my card from {city} that I did not make.",
   "My card was used for ${amount} at a shop I have never visited.",
   "I think my card details were stolen; please block the card."],
  ["Payments I never authorised are showing on my statement from a place I have never been.",
   "Someone else is clearly spending my money and I want the card stopped."],
  ["I still have the card in my wallet but it has been used abroad twice today.",
   "My statement lists purchases made while I was asleep at home."],
  ["fraud", "stolen card"]),
 ("loan_application", "Applying for or asking about loans, mortgages and credit limits", "Existing payment problems",
  ["I would like to apply for a personal loan of ${amount}.",
   "What documents do you need for a mortgage application?",
   "Can I increase the credit limit on my account?"],
  ["We are buying a house and need to know what borrowing we would qualify for.",
   "I want to spread the cost of a large purchase over three years."],
  ["We have found a property and the estate agent wants proof of funds.",
   "My income has doubled and my current limit no longer matches my spending."],
  ["loan", "mortgage"]),
 ("statement_request", "Copies of statements, transaction history and proof of balance", "Disputes about a transaction",
  ["Please send me a statement for the last six months as a PDF.",
   "I need a copy of my transaction history for {month}.",
   "Can you issue a proof of balance letter for my landlord?"],
  ["My accountant has asked for the records covering the first half of the year.",
   "I need written confirmation of what is in the account, on headed paper."],
  ["The letting agency will not process the application without documentation from you.",
   "My tax return is due and I am missing the paperwork for two quarters."],
  ["statement", "transaction history"]),
 ("transfer_issue", "Payments that failed, were delayed or went to the wrong beneficiary", "Card fraud or loan queries",
  ["My transfer to {company} has been pending for three days.",
   "The payment of ${amount} left my account but never arrived at the other bank.",
   "I sent money to the wrong account number; can it be recalled?"],
  ["Funds left my balance on Monday and the recipient still sees nothing.",
   "I typed one digit wrong and the money has gone to a stranger."],
  ["The supplier is chasing me for money that my app says already went out.",
   "The balance dropped but the recipient's confirmation never came."],
  ["transfer", "pending payment"]),
 ("fee_dispute", "Charges applied by the bank: overdraft fees, maintenance fees and interest", "Merchant disputes",
  ["Why was I charged a ${amount} maintenance fee this month?",
   "An overdraft fee appeared even though I was in credit the whole month.",
   "Please explain the interest charge on my current account."],
  ["A deduction with no explanation reduced my balance at the start of the month.",
   "You have taken money for something I never agreed to pay for."],
  ["My balance is lower than the arithmetic of my own payments suggests.",
   "There is a line on the statement that neither I nor my partner recognises as a purchase."],
  ["overdraft fee", "maintenance fee"]),
 ("branch_services", "Appointments, opening hours, cash services and in-branch help", "Anything that can only be done online",
  ["What are the opening hours of your {city} branch on Saturdays?",
   "I would like to book an appointment at the branch next {weekday}.",
   "Does the {city} branch still have a counter for large cash deposits?"],
  ["I need to see somebody in person and want to know when I can come in.",
   "Is there somewhere local where a member of staff can sign my paperwork?"],
  ["I have documents that must be witnessed by a member of your staff.",
   "My grandmother does not use the internet and needs to be served face to face."],
  ["branch", "appointment"]),
]),
"it_helpdesk": ("an internal IT service desk", [
 ("password_reset", "Locked accounts, expired passwords and multi-factor enrolment", "Hardware faults or software purchases",
  ["My domain account is locked after too many failed attempts.",
   "My password expired while I was on leave and I cannot set a new one.",
   "I have a new phone and need to re-enrol my authenticator."],
  ["I am shut out of everything and the self-service page refuses my details.",
   "The code generator lives on a device I no longer own."],
  ["I came back from three weeks away and nothing will let me in this morning.",
   "My old handset was wiped before I moved the six-digit codes across."],
  ["locked account", "authenticator"]),
 ("hardware_fault", "Broken laptops, monitors, docks, keyboards and peripherals", "Software licences or access rights",
  ["My laptop will not charge and the dock light stays off.",
   "The second monitor flickers whenever the dock is plugged in.",
   "The keyboard on my machine has three dead keys."],
  ["The machine runs for twenty minutes and then dies with no warning.",
   "Half of my desk equipment stopped responding after the move."],
  ["There is a smell of hot plastic from the vent on the left side.",
   "The screen shows coloured lines down one side since I dropped the bag."],
  ["laptop", "monitor"]),
 ("software_install", "Requests for applications, licences and package installation", "Faults in software already installed",
  ["Please install the statistics package on my workstation.",
   "I need a licence for the design suite for a project in {month}.",
   "Can you add the VPN client to my new machine?"],
  ["I need a tool I do not currently have in order to finish a piece of work.",
   "Finance approved a seat for me on the drawing program; please set it up."],
  ["My new team uses a program that is not on my machine at all.",
   "The file my colleague sent cannot be opened by anything I have."],
  ["install", "licence"]),
 ("access_request", "Permissions for shared drives, systems and mailboxes", "Password resets",
  ["Please give me read access to the finance shared drive.",
   "I need to be added to the {company} project mailbox.",
   "My role changed; I now need write permission on the reporting system."],
  ["I can see the folder but everything inside it is greyed out for me.",
   "My new duties involve a system that currently refuses to show me anything."],
  ["I moved teams last week and the shared area for my new team is invisible to me.",
   "The rota system shows other departments but not the one I now manage."],
  ["permission", "shared drive"]),
 ("network_outage", "Connectivity problems, Wi-Fi, VPN drops and site-wide outages", "Individual application bugs",
  ["The Wi-Fi on the third floor drops every few minutes.",
   "The VPN disconnects whenever I join a video call.",
   "Nobody in the {city} office can reach the intranet this morning."],
  ["We keep losing the connection in one corner of the building.",
   "Everything on the internal side is unreachable for the whole floor."],
  ["Four of us in the same room lost everything at the same moment.",
   "Pages load at home but not from my desk, on any device."],
  ["Wi-Fi", "VPN"]),
 ("email_issue", "Mail delivery failures, quotas, distribution lists and calendar sync", "Access requests",
  ["Messages to external addresses bounce with a quota error.",
   "My calendar stopped syncing to my phone after the update.",
   "The distribution list for the {city} team no longer reaches everyone."],
  ["Anything I send outside the company comes straight back to me.",
   "Appointments made on the laptop never appear on the handset."],
  ["Colleagues say they never received the note I sent on Monday.",
   "My inbox has not shown anything new since yesterday afternoon."],
  ["mailbox", "calendar sync"]),
]),
"hr": ("a human resources department", [
 ("leave_request", "Booking holiday, parental leave, unpaid leave and absence balances", "Payroll or contract questions",
  ["I would like to book {n} days of annual leave in {month}.",
   "How many holiday days do I have left this year?",
   "I need to request parental leave starting in {month}."],
  ["I want to take time off in the summer and need to know the process.",
   "What is my remaining entitlement for days away from work?"],
  ["My partner and I are planning three weeks abroad in the school holidays.",
   "We are expecting a baby in the spring and I will need time at home."],
  ["annual leave", "holiday"]),
 ("payroll_query", "Salary payments, deductions, tax codes and payslips", "Benefit enrolment",
  ["My salary was ${amount} short this month with no explanation.",
   "The tax code on my payslip changed and I do not know why.",
   "I never received my payslip for {month}."],
  ["The amount that landed in my account does not match my contract.",
   "A deduction I do not recognise has reduced what I take home."],
  ["The figure in my bank app is lower than every previous month this year.",
   "My colleague on the same grade received noticeably more than I did."],
  ["payslip", "salary"]),
 ("benefits_enrolment", "Pension, health cover, cycle schemes and other benefits", "Salary payments",
  ["How do I join the company pension scheme?",
   "I want to add my partner to the health cover.",
   "Is the cycle-to-work scheme still open for applications?"],
  ["I would like to start putting money aside through the workplace arrangement.",
   "My family should be covered by the medical arrangement as well."],
  ["My previous employer put five percent aside for retirement and I want the same here.",
   "My spouse has lost their own cover and needs to be included in mine."],
  ["pension", "health cover"]),
 ("workplace_complaint", "Grievances, harassment, bullying and conduct concerns", "Performance reviews",
  ["I want to raise a formal grievance about my line manager's conduct.",
   "A colleague has been making inappropriate comments in team meetings.",
   "I need to report behaviour that I believe amounts to bullying."],
  ["Something has been happening in my team that I no longer feel able to ignore.",
   "I would like to speak to someone confidentially about how I am being treated."],
  ["Two people in my team now refuse to speak to me and exclude me from meetings.",
   "Remarks about my accent are made openly and everyone laughs."],
  ["grievance", "harassment"]),
 ("onboarding", "New starters, contracts, equipment and first-day logistics", "Leaver processes",
  ["Our new analyst starts on {date}; what do they need to bring?",
   "Please prepare the contract for the candidate who accepted last week.",
   "What does the first-day induction cover for a new starter?"],
  ["Someone is joining my team shortly and I want to be ready for them.",
   "The person who accepted the offer is asking what happens on day one."],
  ["We made an offer on Friday and the candidate signed it the same evening.",
   "A desk, a laptop and a security pass are needed for somebody arriving soon."],
  ["new starter", "induction"]),
 ("training_request", "Courses, certifications, study leave and development budgets", "Onboarding",
  ["I would like to attend a certification course in {month}.",
   "Is there a development budget for external training this year?",
   "Can I take study leave for my professional exams?"],
  ["I want to improve a skill through a course and need to know who approves it.",
   "My exams are in the autumn and I will need days away from the desk."],
  ["My professional body requires a set number of hours of learning each year.",
   "The tooling we adopted last quarter is something nobody on the team knows well."],
  ["course", "certification"]),
]),
"travel": ("a travel agency", [
 ("flight_change", "Rebooking, date changes, missed connections and schedule changes", "Refunds or baggage",
  ["I need to move my flight to {city} to a later date.",
   "My connection was missed because the first leg landed late.",
   "The airline changed the departure time and it no longer works for me."],
  ["The dates of my trip have shifted and the booking must follow.",
   "I arrived at the gate to find the aircraft had already gone."],
  ["My meeting has been pushed back a week and the itinerary no longer fits.",
   "The inbound leg now lands after my onward service departs."],
  ["rebooking", "flight change"]),
 ("baggage_claim", "Lost, delayed or damaged luggage", "Flight changes",
  ["My suitcase did not arrive at {city} with the rest of the flight.",
   "The handle of my case was torn off in transit.",
   "My bag has been missing for four days and nobody has called."],
  ["Everything I packed is somewhere else and I have only what I am wearing.",
   "The case came round the belt with a hole in the side."],
  ["I waited at the carousel until it stopped and nothing of mine appeared.",
   "The zip was broken open and two items are missing from inside."],
  ["luggage", "suitcase"]),
 ("refund_request", "Money back for cancelled or unused travel", "Changing an existing booking",
  ["The trip was cancelled by the operator; I want my money back.",
   "Please refund the ${amount} I paid for the excursion we never took.",
   "I am entitled to a refund because the hotel was closed on arrival."],
  ["I paid for something that never happened and want the payment returned.",
   "The amount I handed over should come back to my card."],
  ["The tour operator folded two days before our departure date.",
   "We turned up to find the property boarded up and had to find a hotel ourselves."],
  ["refund", "money back"]),
 ("booking_enquiry", "Availability, prices, itineraries and new bookings", "Existing booking problems",
  ["Do you have availability in {city} for {n} nights in {month}?",
   "What would a week in {city} for two adults cost?",
   "Can you put together an itinerary for a family of four in {month}?"],
  ["We are thinking about going away and want to know what is possible.",
   "Before we decide, what would that trip come to in total?"],
  ["My parents' anniversary is in the spring and we want to do something special.",
   "We have a free fortnight in the summer and no plans yet."],
  ["availability", "itinerary"]),
 ("visa_documents", "Visas, passports, entry requirements and travel documents", "Insurance",
  ["Do I need a visa for {city} with a passport from another country?",
   "What entry documents are required for travel in {month}?",
   "My passport expires shortly after the return date; is that a problem?"],
  ["I want to be sure my paperwork will get me through the border.",
   "The officials at the other end may want something I do not have."],
  ["My passport has three months left on it and the trip is in eight weeks.",
   "The embassy website is ambiguous about the paperwork for my nationality."],
  ["visa", "passport"]),
 ("travel_insurance", "Policies, cover levels and claims for travel insurance", "Refunds from the operator",
  ["Does my travel policy cover winter sports in {month}?",
   "I want to make a claim on the travel insurance for a cancelled trip.",
   "What level of medical cover does the standard policy include?"],
  ["I want to know whether the protection I bought applies to my activity.",
   "Something went wrong on the trip and I believe the cover should pay out."],
  ["We plan to ski and I am not sure the cover we bought stretches that far.",
   "The hospital abroad charged us and we need to know who pays."],
  ["policy", "cover"]),
]),
"healthcare_admin": ("a hospital administration office", [
 ("appointment_booking", "Making, moving or cancelling appointments and clinic slots", "Test results or billing",
  ["I need to book an appointment with the clinic in {month}.",
   "Please move my appointment on {date} to the following week.",
   "I would like to cancel my slot on {date} and rebook later."],
  ["I need to be seen and want to know when a slot is available.",
   "The time I was given clashes with work and must be changed."],
  ["My referral letter arrived and says to arrange a visit within six weeks.",
   "I will be out of the country on the date I was given."],
  ["appointment", "clinic slot"]),
 ("test_results", "Results of tests, scans and laboratory work", "Booking appointments",
  ["Are the results of my blood test from {date} available yet?",
   "Who do I speak to about the scan results from last week?",
   "My results were promised in five days and it has been three weeks."],
  ["I was told the findings would be ready by now and nobody has been in touch.",
   "The laboratory work I had done should have produced something by now."],
  ["The nurse said someone would call if anything was unusual and nobody has.",
   "My doctor is waiting on paperwork from the laboratory before prescribing."],
  ["test results", "scan"]),
 ("medical_records", "Copies of records, transfers between practices and corrections", "Test results",
  ["Please send a copy of my medical records to my new practice.",
   "I need my records transferred following my move to {city}.",
   "There is an error in my file that needs correcting."],
  ["My new doctor has asked for my history to be forwarded.",
   "Something written in my file is simply wrong and should be amended."],
  ["I registered with a different surgery after moving house last month.",
   "My file lists an allergy I have never had and it worries me."],
  ["records", "file transfer"]),
 ("billing_insurance", "Invoices, insurance claims, co-payments and cost estimates", "Appointments",
  ["I received an invoice for ${amount} that my insurer should have covered.",
   "Can you send the claim directly to my insurance company?",
   "What will the procedure cost me after the insurer's contribution?"],
  ["A bill arrived that I believe somebody else is supposed to settle.",
   "I need an estimate of what I will personally have to pay."],
  ["My cover is supposed to be comprehensive yet a demand for money arrived.",
   "The paperwork from the insurer and the paperwork from you disagree."],
  ["invoice", "insurer"]),
 ("prescription_refill", "Repeat prescriptions, medication changes and pharmacy issues", "Records requests",
  ["I need a repeat prescription for my regular medication.",
   "My prescription ran out and the pharmacy has nothing on file.",
   "Can the dose on my repeat be changed after the last review?"],
  ["I am nearly out of what I take every day and need more.",
   "The chemist says there is no authorisation waiting for me."],
  ["I have four tablets left and the surgery is closed until Monday.",
   "The pharmacist could not dispense anything because nothing was sent through."],
  ["prescription", "medication"]),
 ("complaint_feedback", "Complaints about care, staff conduct and service quality", "Clinical questions",
  ["I want to complain about how I was treated at reception on {date}.",
   "The waiting time was four hours and nobody explained why.",
   "I wish to raise a formal complaint about my care in {month}."],
  ["The way I was dealt with on the day was unacceptable and I want it looked at.",
   "Nobody kept us informed and I would like that recorded formally."],
  ["We sat in the corridor all afternoon while staff walked past without speaking.",
   "My mother was left without water for several hours and nobody checked on her."],
  ["complaint", "waiting time"]),
]),
"telecom": ("a telecoms provider", [
 ("network_coverage", "Signal strength, dropped calls and coverage in an area", "Billing or contracts",
  ["I have no signal at my home address in {city} since {date}.",
   "Calls drop after about a minute on the mobile network here.",
   "Coverage in the village has been unusable for a fortnight."],
  ["The handset shows nothing at all where it used to work perfectly.",
   "Conversations cut out after a minute wherever I stand in the house."],
  ["My neighbours on the same street complain of exactly the same thing.",
   "The bars on the screen have been empty since the mast work started."],
  ["signal", "coverage"]),
 ("broadband_fault", "Slow or broken fixed-line internet, routers and line faults", "Mobile coverage",
  ["My broadband has been down since {date} and the router shows a red light.",
   "The line speed dropped to a fraction of what I pay for.",
   "The connection drops every evening between seven and nine."],
  ["Nothing in the house can get online and the box by the door is flashing.",
   "Downloads that used to take a minute now take most of an hour."],
  ["The engineers dug up the pavement outside and it has not worked since.",
   "The children cannot do their homework in the evenings any more."],
  ["broadband", "router"]),
 ("bill_query", "Charges on the bill, roaming costs and unexpected amounts", "Faults",
  ["My bill is ${amount} this month, far more than usual.",
   "There are roaming charges on the bill for a trip I never took.",
   "Why has the monthly amount increased mid-contract?"],
  ["The demand that arrived is nearly double what I normally hand over.",
   "Items I do not recognise have been added to what I owe."],
  ["The direct debit that went out is far larger than any before it.",
   "My partner and I are on the same plan and were charged very differently."],
  ["bill", "roaming charges"]),
 ("contract_change", "Upgrades, downgrades, renewals and switching plans", "Cancellations",
  ["I would like to upgrade to a plan with more data from {month}.",
   "Can I move to a cheaper tariff before my renewal date?",
   "What happens to my contract if I change the package mid-term?"],
  ["I keep running out of allowance and want a bigger bundle.",
   "The arrangement I am on costs more than I need to spend."],
  ["Working from home has trebled how much I use each month.",
   "My circumstances have changed and my current package no longer fits."],
  ["upgrade", "tariff"]),
 ("cancellation", "Ending service, porting a number away and final bills", "Contract upgrades",
  ["I want to cancel my service at the end of the current term.",
   "Please release my number so I can port it to another provider.",
   "How much notice do I have to give to terminate the agreement?"],
  ["I am leaving and want to know how to close everything down.",
   "My number should move with me to a different company."],
  ["We are emigrating in the spring and will not need the line.",
   "A competitor has offered a package I intend to accept."],
  ["cancel", "port my number"]),
 ("device_support", "Handsets, SIM cards, device settings and repairs", "Network faults",
  ["My SIM card stopped being recognised by the handset.",
   "The phone I bought from you will not hold a charge.",
   "How do I set up the device for the new data settings?"],
  ["The little card in the tray is no longer detected by the phone.",
   "The battery on the handset you sold me lasts barely two hours."],
  ["I put the card into a different phone and that one works fine.",
   "The screen went dark on the second day and will not come back."],
  ["SIM card", "handset"]),
]),
"insurance": ("an insurance company", [
 ("new_claim", "Reporting a new incident and opening a claim", "Policy documents or renewals",
  ["I need to report an accident that happened on {date}.",
   "A storm damaged the roof and I want to open a claim.",
   "My car was hit in a car park and I am claiming for the damage."],
  ["Something happened to my property and I want the process started.",
   "I need to tell you about an incident so the paperwork can begin."],
  ["A tree came through the conservatory during the gales on Sunday.",
   "The other driver drove off and my wing is caved in."],
  ["claim", "incident"]),
 ("claim_status", "Progress of a claim already reported", "New incidents",
  ["What is the status of the claim I reported in {month}?",
   "My claim reference has had no update for three weeks.",
   "Has the assessor's report on my case been received yet?"],
  ["I reported this a while ago and nobody has told me what is happening.",
   "The file I opened earlier seems to have gone quiet."],
  ["The builder is waiting on your decision before starting work.",
   "The hire car company wants to know how much longer they are needed."],
  ["claim status", "assessor"]),
 ("policy_documents", "Certificates, schedules, wording and proof of cover", "Claims",
  ["Please send me a copy of my policy schedule.",
   "I need a certificate of cover for my landlord.",
   "Where can I find the full wording of the policy I bought?"],
  ["My mortgage lender wants written proof of the arrangement.",
   "I would like the detailed terms of what I purchased in writing."],
  ["The letting agent will not hand over the keys without documentation.",
   "I want to check exactly what is excluded before I travel."],
  ["policy schedule", "certificate"]),
 ("renewal_quote", "Renewals, premiums, quotes and mid-term adjustments", "Cancelling cover",
  ["My renewal premium went up by ${amount}; can you requote?",
   "I would like a quote to add a second driver to the policy.",
   "What would the premium be if I increased the excess?"],
  ["The price for the coming year is higher and I want it looked at again.",
   "Adding another person to the arrangement should change the cost."],
  ["My son has just passed his test and will be using the car.",
   "The letter for the coming year arrived with a much larger figure."],
  ["premium", "renewal"]),
 ("cancel_policy", "Ending cover, cooling-off periods and pro-rata refunds", "Renewal quotes",
  ["I want to cancel the policy from the end of {month}.",
   "I have sold the vehicle and no longer need the cover.",
   "Can I cancel within the cooling-off period without a fee?"],
  ["I no longer need this protection and want it stopped.",
   "The item that was covered is gone, so the arrangement should end."],
  ["The house sale completed last week and the new owners have their own arrangement.",
   "We have moved abroad and the vehicle went with the buyer."],
  ["cancel the policy", "cooling-off"]),
 ("complaint_escalation", "Dissatisfaction with a decision and escalation to a review", "New claims",
  ["My claim was rejected and I want the decision reviewed.",
   "I am unhappy with the settlement offered and wish to escalate.",
   "Please pass my complaint to the ombudsman stage."],
  ["The outcome I was given is not acceptable and I want it reconsidered.",
   "I would like somebody more senior to look at how this was handled."],
  ["The figure offered would not replace half of what was destroyed.",
   "Three different people have given me three different explanations."],
  ["rejected", "escalate"]),
]),
"saas_billing": ("a software subscription provider", [
 ("invoice_query", "Questions about invoices, VAT, purchase orders and billing details", "Technical faults",
  ["The invoice for {month} is missing our purchase order number.",
   "Why does this invoice show ${amount} when our contract says less?",
   "Please reissue the invoice with our VAT number on it."],
  ["The document you sent lacks a reference our finance team requires.",
   "The figure on the paperwork does not match what we agreed."],
  ["Our accounts payable system rejects anything without a reference code.",
   "The finance team cannot reclaim the tax without our registration on the document."],
  ["invoice", "purchase order"]),
 ("plan_upgrade", "Moving between tiers, adding seats and feature access", "Cancellations",
  ["We need to add {n} more seats to our subscription.",
   "How do we move from the standard tier to the enterprise tier?",
   "Which plan unlocks single sign-on for our staff?"],
  ["Our team has grown and more people need to use the tool.",
   "The capability we need seems to sit above the level we are on."],
  ["We hired eight people this quarter and everyone needs a login.",
   "Our security team now requires central authentication for every tool."],
  ["seats", "tier"]),
 ("payment_failure", "Declined cards, failed direct debits and dunning", "Refunds",
  ["Our card was declined and the subscription is now past due.",
   "The direct debit failed because the mandate was cancelled by mistake.",
   "We received a dunning email but the card on file is valid."],
  ["The payment did not go through and the account is now flagged.",
   "Money should have been collected this month and was not."],
  ["Our bank replaced every company card last week without telling us.",
   "The account went read-only this morning with no warning."],
  ["declined", "past due"]),
 ("refund_credit", "Refunds, credit notes and pro-rata adjustments", "Failed payments",
  ["We were billed for {n} seats we removed last {month}; please credit us.",
   "Can we have a refund for the duplicate annual charge?",
   "Please issue a credit note for the unused portion of the term."],
  ["We paid for more than we used and would like that money returned.",
   "A credit should be applied for the part of the year we did not use."],
  ["Our headcount dropped in the spring but the charge never changed.",
   "The same amount was taken twice in the same week."],
  ["credit note", "refund"]),
 ("cancel_subscription", "Ending a subscription, non-renewal and data export on exit", "Downgrades",
  ["We will not renew the subscription when it expires in {month}.",
   "Please cancel our account at the end of the current term.",
   "How do we export our data before the subscription ends?"],
  ["We are moving to a different tool and want to close things down.",
   "Before we leave we need everything we have stored taken out."],
  ["The board approved a different platform at the last meeting.",
   "Our contract with you finishes in the spring and will not be extended."],
  ["not renew", "close our account"]),
 ("usage_overage", "Usage limits, overage charges, rate limits and quotas", "Plan upgrades",
  ["We exceeded the API quota and were charged for overage.",
   "Our usage report shows {n} thousand calls above the included allowance.",
   "What is the rate limit on the current plan?"],
  ["We went past the included allowance and a surcharge appeared.",
   "Our consumption is higher than the bundle covers."],
  ["A batch job ran twice by accident overnight and hammered the endpoint.",
   "Traffic tripled after the launch and something started rejecting requests."],
  ["quota", "overage"]),
]),
"logistics": ("a freight and logistics operator", [
 ("shipment_delay", "Late shipments, customs holds and revised ETAs", "Damage claims",
  ["Consignment {ref} has been stuck at the border since {date}.",
   "The delivery window has slipped twice and we need a firm ETA.",
   "Our container has not moved from the port for nine days."],
  ["The load is not where it should be and nobody can say when it will move.",
   "We need a dependable arrival time for goods that are already overdue."],
  ["The production line will stop on Thursday if the parts do not arrive.",
   "The vessel berthed a week ago and nothing has reached the depot."],
  ["delay", "customs hold"]),
 ("damage_claim", "Goods damaged or lost in transit and insurance claims", "Delays",
  ["Two pallets from consignment {ref} arrived crushed.",
   "The driver's notes show water damage on half the cartons.",
   "Three cases are missing from the delivery we signed for."],
  ["Part of the load arrived unusable and we want compensation.",
   "Items that left the warehouse never reached the customer."],
  ["The shrink wrap was torn and the top layer had collapsed inwards.",
   "The seal number on arrival does not match the one on the paperwork."],
  ["damaged", "lost in transit"]),
 ("booking_capacity", "Booking space, vehicle availability and scheduling collections", "Rate quotes",
  ["We need to book a collection from {city} on {date}.",
   "Do you have capacity for {n} pallets next {weekday}?",
   "Please schedule a weekly collection from our {city} site."],
  ["We have goods ready and need a vehicle to come for them.",
   "Is there room on a trailer for our load early next week?"],
  ["Our warehouse is full and the goods must move before the weekend.",
   "We are starting a regular run and need a slot every Tuesday."],
  ["collection", "capacity"]),
 ("rate_quote", "Pricing, surcharges, fuel levies and tariff questions", "Booking capacity",
  ["What is the rate for a full load from {city} to {city2}?",
   "Please quote for {n} pallets on a weekly basis.",
   "How is the fuel surcharge calculated on our lane?"],
  ["We would like a price for moving goods on a regular route.",
   "Costs have risen and we want the calculation explained."],
  ["We are tendering our transport for next year across four routes.",
   "Our finance team cannot reconcile the extra line on each movement."],
  ["rate", "surcharge"]),
 ("customs_docs", "Export paperwork, certificates of origin and commodity codes", "Delays at the border",
  ["Which commodity code applies to the {product} we export?",
   "The certificate of origin for consignment {ref} is missing.",
   "What paperwork is needed for a shipment leaving in {month}?"],
  ["We are unsure which classification our goods fall under.",
   "A document the authorities want was never issued for this load."],
  ["The importer's broker has asked for something we have never produced before.",
   "Our new product line has never been exported and needs classifying."],
  ["commodity code", "certificate of origin"]),
 ("proof_of_delivery", "Signed delivery confirmations, timestamps and receipts", "Damage claims",
  ["Please send the signed proof of delivery for consignment {ref}.",
   "Our customer disputes receiving the goods; we need the signature.",
   "Can you confirm the delivery timestamp for the drop on {date}?"],
  ["We need written confirmation that the goods were handed over.",
   "The receiving party denies it arrived and we need evidence."],
  ["Our customer is withholding payment until the handover is evidenced.",
   "The audit requires the signature sheet for every movement in the quarter."],
  ["proof of delivery", "signature"]),
]),
"education_admin": ("a university administration office", [
 ("enrolment", "Registering for a course, module selection and admission", "Fees",
  ["I would like to enrol on the statistics module for {month}.",
   "How do I register for the coming academic year?",
   "Can I change one of my selected modules before term starts?"],
  ["I want to join a class and need to know how to sign up.",
   "One of the subjects I picked is not what I expected and should be swapped."],
  ["My offer was confirmed last week and I do not know what to do next.",
   "The timetable shows two of my choices at the same hour."],
  ["enrol", "module"]),
 ("tuition_fees", "Fees, instalments, invoices and payment plans", "Scholarships",
  ["My fee invoice shows ${amount}; can I pay in instalments?",
   "When is the deadline for the second fee payment?",
   "I was charged the international rate but I am a local student."],
  ["I cannot pay the whole amount at once and need an arrangement.",
   "The sum being demanded is not the one that applies to me."],
  ["My family can manage monthly amounts but not a single large payment.",
   "I have lived in the country for six years and my status is on file."],
  ["fee invoice", "instalments"]),
 ("transcript_request", "Transcripts, certificates and confirmation of study", "Enrolment",
  ["Please issue an official transcript for my degree.",
   "I need confirmation of study for my visa application.",
   "Can a certified copy of my certificate be sent to an employer?"],
  ["A prospective employer has asked for documentation of my results.",
   "I need something official confirming that I attend the institution."],
  ["The company that offered me a job wants proof before the start date.",
   "The consulate requires paperwork from the institution for my application."],
  ["transcript", "confirmation of study"]),
 ("exam_arrangements", "Exam timetables, resits, special arrangements and deferrals", "Grade appeals",
  ["I need special arrangements for the exam in {month}.",
   "When is the resit sitting for the module I failed?",
   "Can I defer my exam because of a medical appointment on {date}?"],
  ["I require adjustments for the assessment due to a documented condition.",
   "I could not sit the paper and need to know when the next chance is."],
  ["My documented condition means I need extra time in a separate room.",
   "I am having surgery the same week the papers are scheduled."],
  ["resit", "special arrangements"]),
 ("grade_appeal", "Challenging marks, remarking and academic appeals", "Exam arrangements",
  ["I want to appeal the mark I received for the coursework.",
   "Please have my paper remarked; the grade seems inconsistent.",
   "On what grounds can I formally challenge an assessment result?"],
  ["The result I was given does not reflect the work I submitted.",
   "I would like a second examiner to look at what I handed in."],
  ["My two pieces of work were near identical in quality and thirty marks apart.",
   "The feedback describes a submission that is not the one I uploaded."],
  ["appeal", "remark"]),
 ("accommodation", "Halls of residence, room allocation and housing contracts", "Tuition fees",
  ["I would like to apply for a room in halls for {month}.",
   "Can I change rooms because of noise in the current block?",
   "When does the accommodation contract for the year end?"],
  ["I need somewhere to live on campus and want to apply.",
   "Where I am sleeping now is unworkable and I want to move."],
  ["I am moving to the city in the autumn and have nowhere to stay.",
   "The block I am in has building work starting at six every morning."],
  ["halls", "room allocation"]),
]),
"real_estate": ("a property agency", [
 ("viewing_request", "Arranging viewings and visiting properties", "Offers",
  ["I would like to view the property on {date} if possible.",
   "Can we arrange a second viewing of the flat in {city}?",
   "Are evening viewings available next {weekday}?"],
  ["We would like to see the house in person before deciding anything.",
   "Is there a time after work when we could walk round again?"],
  ["We have seen the photographs and want to judge the light ourselves.",
   "My partner could not come last time and needs to see it too."],
  ["viewing", "see the property"]),
 ("offer_negotiation", "Making, raising or withdrawing an offer and negotiations", "Viewings",
  ["We would like to offer ${amount} for the property.",
   "Please put forward an improved offer on our behalf.",
   "We are withdrawing our offer following the survey."],
  ["We are prepared to put a figure forward for the house.",
   "Given what the survey found, we no longer wish to proceed at that price."],
  ["Our mortgage is agreed in principle and we are ready to commit.",
   "The report found damp across two walls and changes what we can pay."],
  ["offer", "negotiation"]),
 ("tenancy_maintenance", "Repairs, maintenance and habitability issues in a rental", "Rent payments",
  ["The boiler in the flat has not worked since {date}.",
   "There is damp spreading across the bedroom wall.",
   "The front door lock is broken and will not secure."],
  ["We have had no hot water for over a week and nobody has come.",
   "Something in the property is broken and needs fixing urgently."],
  ["We are heating the flat with an electric fire because nothing else works.",
   "Black patches have appeared behind the wardrobe and smell strongly."],
  ["repair", "boiler"]),
 ("rent_payment", "Rent amounts, arrears, deposits and payment dates", "Maintenance",
  ["My rent payment of ${amount} did not go through this month.",
   "When is the deposit returned after the tenancy ends?",
   "Can the rent due date be moved to match my pay date?"],
  ["The standing order failed and I want to settle what is owed.",
   "I would like to know when the money held at the start comes back."],
  ["My salary now arrives on the fifth and the collection is on the first.",
   "The bank bounced the transfer because of a card fraud freeze."],
  ["rent", "deposit"]),
 ("contract_terms", "Tenancy agreements, break clauses, renewals and notice", "Repairs",
  ["What notice must I give to leave at the end of the term?",
   "Does the agreement contain a break clause after six months?",
   "Please send the renewal terms for the coming year."],
  ["I want to understand how to end the arrangement properly.",
   "The paperwork for continuing another year should be sent over."],
  ["My job is moving to another city halfway through the year.",
   "The current term finishes in the spring and we would like to stay on."],
  ["notice", "break clause"]),
 ("property_valuation", "Valuations, market appraisals and selling advice", "Offers on other properties",
  ["Could you carry out a valuation of my house in {city}?",
   "What is the current market value of a property like mine?",
   "We are thinking of selling and would like an appraisal."],
  ["I want a professional opinion on what my home would fetch.",
   "Before we decide anything we need a realistic figure for the house."],
  ["We are downsizing next year and need to plan the finances.",
   "Probate requires a written figure for the family home."],
  ["valuation", "appraisal"]),
]),
"food_delivery": ("a food delivery platform", [
 ("missing_items", "Items missing from a delivered order", "Late deliveries",
  ["Two items from my order never arrived in the bag.",
   "The drinks were missing from the delivery I received.",
   "My order was short by one main course."],
  ["Part of what I paid for was simply not in the bag when it arrived.",
   "The courier handed over less than the receipt lists."],
  ["The receipt stapled to the bag lists four things and there were two inside.",
   "We ordered for three people and there was only enough for one."],
  ["missing items", "short order"]),
 ("late_delivery", "Orders arriving late or not at all", "Missing items",
  ["My order is an hour late and the app still says on its way.",
   "The delivery never arrived and the app marked it as completed.",
   "The estimated time has moved back four times."],
  ["Nothing has turned up long after the promised time.",
   "The tracking claims it was handed over but nobody came to the door."],
  ["The food was ordered for seven and it is now nearly nine.",
   "The rider's pin has been stationary two streets away for forty minutes."],
  ["late", "never arrived"]),
 ("food_quality", "Cold, spoiled, incorrect or poorly prepared food", "Missing items",
  ["The food arrived stone cold and inedible.",
   "My meal was prepared with the ingredient I said I am allergic to.",
   "The dish I received is not the one I ordered."],
  ["What turned up was unpleasant and we could not eat it.",
   "The kitchen ignored the note about what I cannot eat."],
  ["Everything in the container had congealed by the time it reached us.",
   "There were nuts through the sauce and the order clearly said otherwise."],
  ["cold food", "wrong dish"]),
 ("refund_request", "Money back for an unsatisfactory or undelivered order", "Complaints without a money request",
  ["Please refund the ${amount} I paid for that order.",
   "I want my money back for the meal that never came.",
   "Refund the order placed on {date}; it was unusable."],
  ["I would like the payment for that order returned to my card.",
   "The amount taken should come back given nothing usable arrived."],
  ["We ended up cooking at home and still paid you for nothing.",
   "The entire order went straight into the bin."],
  ["refund", "money back"]),
 ("account_promo", "Accounts, promotional codes, credits and loyalty schemes", "Order problems",
  ["My promotional code was rejected at checkout.",
   "The credit from last week has disappeared from my account.",
   "How do I join the loyalty scheme?"],
  ["The discount I was sent would not apply when I tried to use it.",
   "A balance that was on my profile is no longer showing."],
  ["The email said twenty percent off and the total did not change.",
   "The compensation I was promised after the last order is nowhere to be seen."],
  ["promo code", "credit"]),
 ("courier_conduct", "Behaviour of the delivery rider and safety concerns", "Food quality",
  ["The rider was rude and shouted at my neighbour.",
   "The courier left the bag in the rain without ringing the bell.",
   "The driver parked across a driveway and refused to move."],
  ["The person delivering behaved in a way I want reported.",
   "Our food was abandoned outside in bad weather without a word."],
  ["My neighbour was sworn at on her own doorstep by somebody in your uniform.",
   "The bag was found soaked on the path an hour after it was marked delivered."],
  ["rider", "courier behaviour"]),
]),
"utilities": ("an energy and water utility", [
 ("meter_reading", "Submitting readings, meter accuracy and estimated bills", "Payment plans",
  ["I would like to submit a meter reading of {n} for this quarter.",
   "My bill is estimated again although I sent a reading in {month}.",
   "I think the meter is over-recording; can it be tested?"],
  ["I want to give you the figure from the dial so the bill is accurate.",
   "The amounts are still based on a guess rather than the actual figure."],
  ["The number on the box by the door is far lower than your letter assumes.",
   "Usage supposedly doubled in a quarter when the house was empty."],
  ["meter reading", "estimated bill"]),
 ("supply_outage", "Power cuts, water interruptions and restoration times", "Billing",
  ["The power has been off in my street since {date}.",
   "There is no water at the property and no notice was given.",
   "When will supply be restored in the {city} area?"],
  ["Nothing is coming through to the house and neighbours are affected too.",
   "We need to know how long we will be without anything."],
  ["Every house on our side of the road is in darkness this evening.",
   "The taps have been dry since breakfast and the street is flooded."],
  ["outage", "power cut"]),
 ("payment_plan", "Arrears, instalments, hardship arrangements and direct debits", "Meter readings",
  ["I cannot pay the ${amount} balance at once; can we arrange instalments?",
   "Please set up a monthly direct debit for my account.",
   "I have fallen behind and need a repayment arrangement."],
  ["I need to spread what I owe over several months.",
   "Money is tight and I want to agree a manageable schedule."],
  ["I lost my job in the spring and the balance has built up since.",
   "The quarterly demand is more than I earn in a fortnight."],
  ["instalments", "arrears"]),
 ("tariff_switch", "Changing tariff, fixed rates and switching supplier", "Payment plans",
  ["I want to move to a fixed tariff from {month}.",
   "What rates are available if I switch my plan?",
   "I am transferring to another supplier from {date}."],
  ["I would like to change the pricing arrangement I am on.",
   "I am moving my account to a different company shortly."],
  ["My current deal expires in the spring and I want certainty on price.",
   "A comparison site suggests I could pay considerably less elsewhere."],
  ["tariff", "switch supplier"]),
 ("connection_move", "New connections, moving home and final readings", "Outages",
  ["We move house on {date} and need the account transferred.",
   "Please set up a new supply at my new address in {city}.",
   "I need a final reading taken when I leave the property."],
  ["We are relocating and the account should follow us.",
   "A fresh supply is needed at a property we are taking over."],
  ["Completion is at the end of the month and the keys change hands then.",
   "The new-build has no account with anybody yet."],
  ["moving home", "new connection"]),
 ("leak_safety", "Gas smells, leaks, damaged equipment and safety hazards", "Tariff questions",
  ["There is a strong smell of gas near the meter cupboard.",
   "Water is coming up through the pavement outside the house.",
   "A cable has come down across the garden and is sparking."],
  ["Something dangerous is happening at the property and needs attention now.",
   "There is an obvious hazard outside that somebody must attend to."],
  ["The whole street can smell it and we have opened every window.",
   "A fountain has appeared in the road and the pressure indoors has dropped."],
  ["gas smell", "leak"]),
]),
"government": ("a local government service centre", [
 ("permit_application", "Applying for permits, licences and planning permission", "Tax bills",
  ["I want to apply for a parking permit for {city} zone {n}.",
   "What is required for planning permission for a rear extension?",
   "How do I apply for a street trading licence?"],
  ["I need official authorisation to do something at my property.",
   "I would like to know the process for getting approval to trade."],
  ["We intend to build a single-storey addition at the back of the house.",
   "Our new neighbours have a document that lets them park on the street and we do not."],
  ["permit", "planning permission"]),
 ("tax_billing", "Council tax, rates, discounts and payment arrangements", "Benefits",
  ["My council tax bill is ${amount}; am I entitled to a single-person discount?",
   "Please set up a twelve-month payment arrangement for my rates.",
   "The band on my property looks wrong compared with next door."],
  ["The annual demand arrived and I believe a reduction should apply.",
   "I would like to pay the yearly amount in smaller monthly sums."],
  ["I live alone since my partner moved out in the spring.",
   "Identical houses on our road are assessed two categories apart."],
  ["council tax", "billing band"]),
 ("waste_collection", "Bin collections, missed pickups, recycling and bulky waste", "Street cleaning",
  ["My bin was not emptied on the scheduled day again.",
   "How do I arrange collection of a bulky item such as a sofa?",
   "The recycling has been missed for three weeks in a row."],
  ["The lorry went past our street without stopping once more.",
   "We have a large piece of furniture that needs taking away."],
  ["Everyone on the road still has full containers at the kerb this evening.",
   "An old mattress has been in the garden since the new bed arrived."],
  ["bin collection", "recycling"]),
 ("benefits_support", "Housing benefit, hardship funds and welfare support", "Council tax billing",
  ["I would like to apply for housing support after losing my job.",
   "What evidence is needed for a hardship fund application?",
   "My circumstances changed and my entitlement should be reassessed."],
  ["I need financial help with my rent following a change at work.",
   "My income has dropped and I want my assessment looked at again."],
  ["My hours were cut to eight a week and I cannot cover the rent.",
   "My partner has moved out and our household income has halved."],
  ["housing benefit", "hardship fund"]),
 ("road_maintenance", "Potholes, street lighting, signage and road repairs", "Waste collection",
  ["There is a deep pothole outside number {n} on our road.",
   "The street light at the junction has been out for a month.",
   "A road sign has been knocked over and is lying in the verge."],
  ["The surface of our road is dangerous and needs attention.",
   "It is pitch dark at the corner every night since the lamp failed."],
  ["A cyclist came off outside our house last night because of the hole.",
   "Two cars have had tyres burst at the same spot this month."],
  ["pothole", "street light"]),
 ("records_registry", "Birth, marriage and death certificates and electoral registration", "Permits",
  ["I need a certified copy of a birth certificate.",
   "How do I register to vote at my new address?",
   "Please advise how to obtain a marriage certificate copy."],
  ["I require an official copy of a document held in the registry.",
   "Having moved, I want to be added to the electoral roll here."],
  ["The passport office has asked for a document I no longer possess.",
   "We moved in the autumn and never updated our details for elections."],
  ["certificate", "electoral roll"]),
]),
}

FRAMES = [
    "{ph}",
    "Hello. {ph}",
    "Hi there. {ph} Thanks in advance.",
    "Good morning. {ph} Please advise.",
    "{ph} Could you look into this today?",
    "I am writing about an ongoing matter. {ph}",
    "{ph} I would appreciate a quick reply.",
    "Following up on my earlier message. {ph}",
    "Hi, hope you are well. {ph}",
    "{ph} Let me know what the next step is.",
    "To whom it may concern: {ph}",
    "{ph} My reference is {ref}.",
    "Sorry to bother you again. {ph}",
    "{ph} Regards, {person}.",
    "Message received on the {channel} channel: {ph}",
    "{ph} I have nothing else to add for now.",
]

DISTRACTOR_FRAMES = [
    "A colleague mentioned {kw} in passing, but that is not why I am writing.",
    "Earlier this year I had a separate matter about {kw} which was resolved.",
    "Your newsletter had a section on {kw} that I skimmed over breakfast.",
    "Please ignore the {kw} line in my signature, it is out of date.",
    "Someone on the community forum asked about {kw} the other day.",
    "The confirmation email also mentions {kw} at the very bottom.",
    "My colleague {person} handles {kw} matters, not me.",
    "Unrelated, but the help page about {kw} could be clearer.",
]

NEG_FRAMES = [
    "This is not about {kw} - that part is fine. {ph}",
    "I am not asking about {kw}. {ph}",
    "To be clear, my question has nothing to do with {kw}. {ph}",
    "Nothing to do with {kw} this time. {ph}",
    "Let me be precise: not {kw}. {ph}",
    "Please skip the {kw} angle, it does not apply here. {ph}",
]

INSTRUCTIONS = [
    "Which team should handle this message?",
    "Route this message to the responsible team.",
    "Which department is responsible for this request?",
    "Pick the queue this conversation belongs in.",
    "Classify the customer's primary request.",
    "Which of these teams owns this enquiry?",
    "Assign this contact to one team.",
    "Which handler should take this conversation?",
]

FALLBACKS = [
    ("other", "None of the above; unrelated to anything this team handles"),
    ("none_of_the_above", "The message does not fit any listed team"),
    ("unclear", "The message is not about any of the listed areas"),
    ("general_enquiry", "Nothing in the listed areas applies to this message"),
]

OFFTOPIC = [
    "Do you know a good recipe for banana bread? My oven runs a little hot.",
    "What time does the maritime museum open on Sundays? We are visiting soon.",
    "My neighbour's dog barks all night and I cannot sleep at all.",
    "Could you recommend a novel similar to the one I read last summer?",
    "The match ended in a draw and the referee was dreadful throughout.",
    "Which hiking trails near the lake stay open through the winter?",
    "How many calories are in a bowl of oatmeal with honey on top?",
    "My tomato plants have yellow leaves; is that too much water?",
    "Is there a decent guitar teacher in the area who takes beginners?",
    "We are repainting the hallway and cannot choose between two greens.",
    "Does anyone still repair mechanical typewriters these days?",
    "What is the best month to see the northern lights from a ship?",
]


def _fill(ctx, rng, s):
    return s.format(
        product=ctx.slot(rng, "product"), amount="%.2f" % ctx.slot(rng, "amount"),
        n=ctx.slot(rng, "small"), city=ctx.slot(rng, "city"), city2=ctx.slot(rng, "city"),
        month=ctx.slot(rng, "month"), weekday=ctx.slot(rng, "weekday"),
        date=core.pretty_date(ctx.date(rng)), ref=ctx.ticket_id(rng),
        person=ctx.slot(rng, "person"), channel=ctx.slot(rng, "channel"),
        company=ctx.slot(rng, "company"),
    )


def _criteria(ctx, rng, keys, intents, form):
    crit = {}
    for k in keys:
        what, notf, _ph, _pa, _si, kws = intents[k]
        if form == "object":
            crit[k] = {"what": what, "not_for": notf, "examples": [kws[0], kws[-1]]}
        elif form == "null":
            crit[k] = None
        else:
            crit[k] = what
    return crit


DOM_KEYS = sorted(DOMAINS)


def scenarios(ctx, limit=None):
    """Yield lists of records, one list per (domain, intent, repeat) scenario."""
    emitted = 0
    rep = 0
    while True:
        for dom in DOM_KEYS:
            ctxt, intent_list = DOMAINS[dom]
            intents = {k: v for (k, v) in [(i[0], i[1:]) for i in intent_list]}
            ikeys = [i[0] for i in intent_list]
            for ik in ikeys:
                ctx.reset_tids()
                rng = ctx.rng("ir", dom, ik, rep)
                what, notf, ph, para, sit, kws = intents[ik]
                frame_tid, frame = ctx.pick(rng, "ir/frames", FRAMES)
                ctx.use(frame_tid)
                ph_tid, ph_s = ctx.pick(rng, "ir/ph/%s/%s" % (dom, ik), ph)
                ctx.use(ph_tid)
                pa_tid, pa_s = ctx.pick(rng, "ir/para/%s/%s" % (dom, ik), para)
                ctx.use(pa_tid)
                si_tid, si_s = ctx.pick(rng, "ir/sit/%s/%s" % (dom, ik), sit)
                ctx.use(si_tid)
                nopts = rng.choice([4, 5, 6])
                others = [k for k in ikeys if k != ik]
                rng.shuffle(others)
                opts = others[:nopts - 1] + [ik]
                rng.shuffle(opts)
                decoy = others[0]
                dkw = intents[decoy][5][rng.randrange(len(intents[decoy][5]))]
                ev_plain = _fill(ctx, rng, ph_s)
                base = _fill(ctx, rng, frame.replace("{ph}", "\x00PH\x00")).replace(
                    "\x00PH\x00", ev_plain)
                group = "ir/%s/%s/%d" % (dom, ik, rep)
                rid = "%s-ir-%s-%s-%d" % (ctx.stream, dom, ik, rep)
                tids = list(ctx.cur_tids)
                recs = []

                def chk(value, options, rule="choice_const", args=None):
                    a = {"value": value, "options": sorted(options)}
                    if args:
                        a.update(args)
                    return [{"qid": "intent", "rule": rule, "args": a}]

                form = rng.choice(["string", "object", "string", "null"])
                q = {"type": "choice", "instructions": ctx.pick_val(rng, "ir/instr", INSTRUCTIONS),
                     "criteria": _criteria(ctx, rng, opts, intents, form)}
                recs.append(ctx.rec(rid, FAMILY, "intent_routing", "plain", group,
                                    base, {"intent": q}, {"intent": ik}, "easy", "lexical",
                                    chk(ik, opts), evidence=[ev_plain]))
                # option permutation (same scenario, stability probe)
                qp = {"type": "choice", "instructions": q["instructions"],
                      "criteria": core.shuffled_map(rng, dict(reversed(list(q["criteria"].items()))))}
                recs.append(ctx.rec(rid + "-perm", FAMILY, "intent_routing", "option_permutation",
                                    group, base, {"intent": qp}, {"intent": ik}, "easy", "lexical",
                                    chk(ik, opts), evidence=[ev_plain]))
                # paraphrase: avoids the gold option's own keywords
                pmsg = _fill(ctx, rng, pa_s)
                qo = {"type": "choice", "instructions": q["instructions"],
                      "criteria": _criteria(ctx, rng, opts, intents, "object")}
                recs.append(ctx.rec(rid + "-para", FAMILY, "intent_routing", "paraphrase", group,
                                    pmsg, {"intent": qo}, {"intent": ik}, "standard", "paraphrase",
                                    chk(ik, opts), evidence=[pmsg]))
                # distractor sentences carrying a wrong option's keywords
                df = ctx.pick_val(rng, "ir/dframes", DISTRACTOR_FRAMES).format(
                    kw=dkw, person=ctx.slot(rng, "person"))
                df2 = ctx.pick_val(rng, "ir/dframes", DISTRACTOR_FRAMES).format(
                    kw=intents[others[1 % len(others)]][5][0], person=ctx.slot(rng, "person"))
                dmsg = core.sent_join([df, base, df2])
                recs.append(ctx.rec(rid + "-distract", FAMILY, "intent_routing", "distractor",
                                    group, dmsg, {"intent": q}, {"intent": ik}, "standard", "lexical",
                                    chk(ik, opts, args={"decoy_keywords": [dkw]}), evidence=[ev_plain]))
                # negated contrast
                nf = ctx.pick_val(rng, "ir/nframes", NEG_FRAMES).format(kw=dkw, ph=_fill(ctx, rng, ph_s))
                recs.append(ctx.rec(rid + "-neg", FAMILY, "intent_routing", "negated_contrast",
                                    group, nf, {"intent": q}, {"intent": ik}, "hard", "negation",
                                    chk(ik, opts, rule="negated_contrast",
                                        args={"decoy": decoy, "target": ik}), evidence=[nf]))
                # implicit intent: a situation, no keyword
                imsg = _fill(ctx, rng, si_s)
                recs.append(ctx.rec(rid + "-impl", FAMILY, "intent_routing", "implicit", group,
                                    imsg, {"intent": qo}, {"intent": ik}, "hard", "implicit",
                                    chk(ik, opts), evidence=[imsg]))
                # fallback option, sometimes gold
                fbk, fbd = ctx.pick_val(rng, "ir/fallbacks", FALLBACKS)
                offtopic = (rep + core.hint("ir/" + dom + "/" + ik, 2)) % 2 == 0 and rng.random() < 0.55
                fcrit = _criteria(ctx, rng, opts, intents, "string")
                fcrit[fbk] = fbd
                fcrit = core.shuffled_map(rng, fcrit)
                fq = {"type": "choice",
                      "instructions": "%s Use the fallback option when nothing else applies." % q["instructions"],
                      "criteria": fcrit}
                fmsg = ctx.pick_val(rng, "ir/offtopic", OFFTOPIC) if offtopic else base
                recs.append(ctx.rec(rid + "-fb", FAMILY, "intent_routing", "fallback_option", group,
                                    fmsg, {"intent": fq}, {"intent": fbk if offtopic else ik},
                                    "hard", "implicit" if offtopic else "lexical",
                                    [{"qid": "intent", "rule": "fallback",
                                      "args": {"offtopic": bool(offtopic), "intent": ik,
                                               "fallback_key": fbk,
                                               "options": sorted(fcrit)}}],
                                    evidence=[fmsg]))
                for r in recs:
                    r["meta"]["template_ids"] = sorted(set(tids + r["meta"]["template_ids"]))
                    r["meta"]["domain"] = dom
                    r["meta"]["pad_family"] = "ticket"
                emitted += len(recs)
                yield recs
                if limit and emitted >= limit:
                    return
        rep += 1
        if rep > 400:
            return
