#!/usr/bin/env bash
# Feature-group ablations: retrain + recalibrate with a feature group zeroed,
# evaluate on the internal dev split, write reports/ablations.md.
# Usage: scripts/ablation.sh [TRAIN...] -- [CALIB...] -- [DEV...]
set -euo pipefail
cd "$(dirname "$0")/.."
BIN=./target/release/sextant
TMP="${TMPDIR:-/tmp}/sextant-ablation"
mkdir -p "$TMP" reports
TRAIN=(); CALIB=(); DEV=()
mode=train
for a in "$@"; do
  if [ "$a" = "--" ]; then
    if [ $mode = train ]; then mode=calib; else mode=dev; fi; continue; fi
  case $mode in train) TRAIN+=("$a");; calib) CALIB+=("$a");; dev) DEV+=("$a");; esac
done
[ ${#TRAIN[@]} -eq 0 ] && TRAIN=(data/synthetic/train.jsonl)
[ ${#CALIB[@]} -eq 0 ] && CALIB=(data/synthetic/calib.jsonl)
[ ${#DEV[@]} -eq 0 ] && DEV=(data/synthetic/dev.jsonl)

declare -A FGROUPS=(
  [none]=""
  [lexical_graph]="syn_cov,hyper_match,domain_match,antonym_hits,antonym_negated"
  [char_ngrams]="gram_dice_best,gram_cov"
  [negation_modality]="neg_agree,neg_conflict,hyp_conflict,hyp_state,req_agree,neg_field_cov,neg_field_best,antonym_negated"
  [literals]="literal_hit,literal_len,literal_count,focus_literal"
  [sentiment_intensity]="valence_agree,valence_abs,intensity_dist,intensity_cov,ord_pos_int,ord_pos_val,ord_hit"
  [cross_field]="xfield_available,xfield_cov_ab,xfield_cov_ba,xfield_jaccard,xfield_cos,xfield_gram,xfield_neg_conflict,xfield_antonym,xfield_num_conflict,x_sim_pos,x_conflict_neg,x_low_neutral,opt_neg_share,opt_hyp_share"
  [retrieval_core]="bm25_best,bm25_global,cos_global,cos_best,jaccard_best,bigram_hits"
  [coverage]="cov_w,cov_best,cov_rare,cov_name,focus_cov"
  [examples]="example_max,example_mean"
  [directive]="directive_frac"
  [numeric_window]="range_hit,range_dist,window_ok"
  [structural]="evidence_density,term_count_log,ood,null_desc,key_match,key_negated,q_cov_best"
)
ORDER=(none lexical_graph char_ngrams negation_modality literals sentiment_intensity cross_field retrieval_core coverage examples directive numeric_window structural)
OUT=reports/ablations.md
{
  echo "# Feature-group ablations (internal dev split)"
  echo
  echo "Each row retrains and recalibrates with the listed features zeroed during training (they then carry zero weight at inference). Symbolic resolvers are unaffected. Generated by scripts/ablation.sh on $(date -u +%Y-%m-%dT%H:%MZ), commit $(git rev-parse --short HEAD)."
  echo
  echo "| dropped group | features | acc | NLL | Brier | ECE | choice acc | score acc | noul acc |"
  echo "|---|---|---|---|---|---|---|---|---|"
} > "$OUT"
for g in "${ORDER[@]}"; do
  feats="${FGROUPS[$g]}"
  dir="$TMP/$g"; rm -rf "$dir"; mkdir -p "$dir"
  if [ -z "$feats" ]; then
    $BIN train "${TRAIN[@]}" --out-dir "$dir" >/dev/null 2>&1
  else
    $BIN train "${TRAIN[@]}" --out-dir "$dir" --drop-features "$feats" >/dev/null 2>&1
  fi
  $BIN calibrate "${CALIB[@]}" --out-dir "$dir" >/dev/null 2>&1
  $BIN --model-dir "$dir" eval "${DEV[@]}" --group-by family --out "$dir/eval.json" >/dev/null 2>&1
  python3 - "$dir/eval.json" "$g" "$feats" >> "$OUT" <<'PY'
import json, sys
r = json.load(open(sys.argv[1])); o = r["overall"]; k = r["by_kind"]
def acc(kind): return f"{k[kind]['accuracy']:.3f}" if kind in k else "-"
print(f"| {sys.argv[2]} | {sys.argv[3] or '(full model)'} | {o['accuracy']:.3f} | {o['nll']:.3f} | {o['brier']:.3f} | {o['ece']:.3f} | {acc('choice')} | {acc('score')} | {acc('noul')} |")
PY
  echo "$g done"
done
cat "$OUT"
